/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import java.net.URISyntaxException;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.context.embedded.EmbeddedServletContainerFactory;
import org.springframework.boot.context.embedded.tomcat.TomcatConnectorCustomizer;
import org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory;
import org.springframework.context.annotation.Bean;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@EnableAutoConfiguration
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        SpringApplication.run(App.class, args);

    }

    @RequestMapping("/")
    String home() {
        return "Hello World!";
    }

    @Bean
    public EmbeddedServletContainerFactory servletContainer() throws URISyntaxException {

        TomcatEmbeddedServletContainerFactory factory =
                new TomcatEmbeddedServletContainerFactory(8888);


        return factory;
    }

}
